# Generated by Django 5.0.4 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookName',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
